[package]
name = "css-modules-kit-zed"
version = "0.0.1"
edition = "2024"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
zed_extension_api = "0.5.0"
