packages:
  - 'packages/*'
  - 'crates/*'
allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: false
blockExoticSubdeps: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
minimumReleaseAge: 4320
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
