packages:
  - 'packages/*'
  - 'crates/*'
allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: false
blockExoticSubdeps: true
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@mizdra/*'
overrides:
  vite: '$vite'
  vitest: '$vitest'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
