name: 'Setup Node and pnpm store cache'
description: 'Setup pnpm, Node.js, and restore pnpm store cache'
inputs:
  node-version:
    description: 'Node.js version'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v5
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
      shell: sh
