name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  VSCODE_VERSION: '1.103.0'

jobs:
  lint:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-node-and-node-modules
        with:
          node-version: 22
      - run: pnpm run lint
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-node-and-node-modules
        with:
          node-version: 22
      - run: pnpm run build
  test:
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
        os: [ubuntu-24.04-arm, macos-latest, windows-11-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-node-and-node-modules
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            node_modules/.vite/vitest
            packages/*/dist
            packages/*/tsconfig.build.tsbuildinfo
            tsconfig.tsbuildinfo
          key: test-tools-${{ runner.arch }}-${{ runner.os }}-node-${{ matrix.node }}-${{ github.sha }}
          restore-keys: test-tools-${{ runner.arch }}-${{ runner.os }}-node-${{ matrix.node }}
      - run: pnpm run test
  test-stylelint-v16:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
      - run: pnpm add -D -w stylelint@16
      - uses: ./.github/actions/setup-node-and-node-modules
        with:
          node-version: 22
      - run: pnpm run test -- packages/stylelint-plugin
  vscode-test:
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
        os: [ubuntu-24.04-arm, macos-latest, windows-11-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-node-and-node-modules
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            packages/*/dist
            packages/*/tsconfig.build.tsbuildinfo
            tsconfig.tsbuildinfo
          key: test-vscode-tools-${{ runner.arch }}-${{ runner.os }}-node-${{ matrix.node }}-${{ github.sha }}
          restore-keys: test-vscode-tools-${{ runner.arch }}-${{ runner.os }}-node-${{ matrix.node }}
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: .vscode-test
          key: vscode-test-${{ runner.arch }}-${{ runner.os }}-vscode-${{ env.VSCODE_VERSION }}

      - run: xvfb-run -a pnpm run vscode-test
        if: runner.os == 'Linux'
      - run: pnpm run vscode-test
        if: runner.os != 'Linux'
