name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # Required for npm trusted publishing with OIDC
  contents: write # Required for changesets/action
  pull-requests: write # Required for changesets/action

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: voidzero-dev/setup-vp@8ecb39174989ce55af90f45cf55b02738599831d # v1.6.0
        with:
          node-version: 24
          cache: true
      - run: vp run build
      - name: set release variables
        run: echo "date=$(date -u +'%Y-%m-%dT%H:%MZ')" >> $GITHUB_ENV
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: dotansimha/changesets-action@069996e9be15531bd598272996fa23853d61590e # v1.5.2
        with:
          version: vp run version
          publish: vp exec changeset publish
          createGithubReleases: aggregate
          githubReleaseName: Release ${{ env.date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
      - run: vp exec vsce publish --no-git-tag-version --skip-duplicate
        if: steps.changesets.outputs.hasChangesets == 'false'
        working-directory: packages/vscode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - run: vp exec ovsx publish --skip-duplicate
        if: steps.changesets.outputs.hasChangesets == 'false'
        working-directory: packages/vscode
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
